# Generated by Django 3.2.8 on 2021-10-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='measurement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
