# Generated by Django 3.2.8 on 2021-10-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_recipeingredients_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='measurement',
            field=models.CharField(max_length=100),
        ),
    ]
